### ISSUE TITLE
Reporte animación objeto 3D 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-magaly#1]
[reporte de animacion 3d_desarrollo de realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-magaly/files/14923399/reporte.de.animacion.3d_desarrollo.de.realidad.aumentada.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
